# Generated by Django 5.2.16 on 2026-07-31 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('state', models.CharField(choices=[('new', 'New'), ('triage', 'Triage'), ('containment', 'Containment'), ('eradication', 'Eradication'), ('recovery', 'Recovery'), ('closed', 'Closed')], default='new', max_length=20)),
                ('category', models.CharField(blank=True, default='general', max_length=80)),
                ('source', models.CharField(blank=True, default='manual', max_length=80)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('iocs', models.JSONField(blank=True, default=list)),
                ('mitre_tactics', models.JSONField(blank=True, default=list)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_incidents', to='service_desk.company')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incident', to='service_desk.ticket')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SOCPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soc_playbooks', to='service_desk.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PlaybookRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('log', models.JSONField(blank=True, default=list)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('security_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_runs', to='soc_center.securityincident')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='soc_center.socplaybook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
