# Generated by Django 5.2.16 on 2026-07-31 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('email_imap', 'Email IMAP'), ('ldap', 'LDAP / AD'), ('m365', 'Microsoft 365'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('sms', 'SMS'), ('custom', 'Custom')], max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('state', models.CharField(choices=[('configured', 'Configured'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled')], default='configured', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='service_desk.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'name'],
                'unique_together': {('company', 'provider', 'name')},
            },
        ),
    ]
