# Generated by Django 5.2.16 on 2026-07-31 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=60)),
                ('entity_type', models.CharField(default='ticket', help_text='ticket | change | purchase_request', max_length=40)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('min_approvers', models.PositiveSmallIntegerField(default=1)),
                ('approver_role', models.CharField(blank=True, default='approver', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_policies', to='service_desk.company')),
            ],
            options={
                'verbose_name_plural': 'approval policies',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
