# Generated by Django 5.2.16 on 2026-07-31 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('cidr', models.CharField(help_text='e.g. 10.0.0.0/24', max_length=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('hosts_found', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_scans', to='service_desk.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('os_guess', models.CharField(blank=True, max_length=120)),
                ('is_alive', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_hosts', to='service_desk.company')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='network_discovery.discoveryscan')),
            ],
            options={
                'ordering': ['ip_address'],
                'unique_together': {('scan', 'ip_address')},
            },
        ),
    ]
