# Generated by Django 5.2.16 on 2026-07-31 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('communication', 'Communication'), ('monitoring', 'Monitoring'), ('identity', 'Identity'), ('devops', 'DevOps'), ('productivity', 'Productivity'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=30)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='fa-puzzle-piece', max_length=60)),
                ('version', models.CharField(default='1.0.0', max_length=40)),
                ('config_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema describing required configuration keys.')),
                ('webhook_events', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('documentation_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('installed', 'Installed'), ('disabled', 'Disabled'), ('error', 'Error')], default='installed', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_apps', to='service_desk.company')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='marketplace.marketplaceapp')),
            ],
            options={
                'ordering': ['app__name'],
                'unique_together': {('company', 'app')},
            },
        ),
    ]
