# Generated by Django 5.2.16 on 2026-07-31 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('change_management', '0001_initial'),
        ('service_desk', '0001_initial_enterprise_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('build', 'Build'), ('test', 'Test'), ('ready', 'Ready for deployment'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('deployment_notes', models.TextField(blank=True)),
                ('rollback_notes', models.TextField(blank=True)),
                ('changes', models.ManyToManyField(blank=True, related_name='releases', to='change_management.changerequest')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='service_desk.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planned_start', '-created_at'],
                'unique_together': {('company', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ReleaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_tasks', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='release_management.release')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
    ]
