# Generated by Django 5.2.16 on 2026-07-31 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='dashboard', max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='service_desk.company')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['company', 'period_end'], name='analytics_e_company_ccda97_idx')],
            },
        ),
    ]
