"""Default plan catalog definitions."""

from decimal import Decimal

DEFAULT_PLANS = [
    {
        "code": "free",
        "name": "Free",
        "tier": "free",
        "description": "For evaluation teams",
        "price_monthly": Decimal("0.00"),
        "price_yearly": Decimal("0.00"),
        "max_agents": 2,
        "max_tickets_per_month": 50,
        "max_assets": 25,
        "features": ["ticketing", "knowledge"],
        "sort_order": 10,
    },
    {
        "code": "starter",
        "name": "Starter",
        "tier": "starter",
        "description": "Small IT teams",
        "price_monthly": Decimal("49.00"),
        "price_yearly": Decimal("490.00"),
        "max_agents": 10,
        "max_tickets_per_month": 1000,
        "max_assets": 250,
        "features": ["ticketing", "knowledge", "sla", "api"],
        "sort_order": 20,
    },
    {
        "code": "professional",
        "name": "Professional",
        "tier": "professional",
        "description": "Growing service desks",
        "price_monthly": Decimal("149.00"),
        "price_yearly": Decimal("1490.00"),
        "max_agents": 50,
        "max_tickets_per_month": 10000,
        "max_assets": 2000,
        "features": [
            "ticketing",
            "knowledge",
            "sla",
            "api",
            "cmdb",
            "automation",
            "change",
            "problem",
        ],
        "sort_order": 30,
    },
    {
        "code": "enterprise",
        "name": "Enterprise",
        "tier": "enterprise",
        "description": "Unlimited scale with premium support",
        "price_monthly": Decimal("499.00"),
        "price_yearly": Decimal("4990.00"),
        "max_agents": 1000,
        "max_tickets_per_month": 1000000,
        "max_assets": 100000,
        "features": [
            "ticketing",
            "knowledge",
            "sla",
            "api",
            "cmdb",
            "automation",
            "change",
            "problem",
            "sso",
            "mfa",
            "ai",
            "discovery",
            "multi_tenant",
        ],
        "sort_order": 40,
    },
]