from django.urls import path
from . import views

app_name = 'service_desk'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('tickets/', views.TicketListView.as_view(), name='ticket_list'),
    path('tickets/new/', views.TicketCreateView.as_view(), name='ticket_create'),
    path('tickets/<int:pk>/', views.TicketDetailView.as_view(), name='ticket_detail'),
    path('tickets/<int:pk>/assign/', views.TicketAssignView.as_view(), name='ticket_assign'),
    path('tickets/<int:pk>/status/', views.TicketStatusChangeView.as_view(), name='ticket_status_change'),
    path('tickets/<int:pk>/request-confirmation/', views.TicketRequestConfirmationView.as_view(), name='ticket_request_confirmation'),
    path('tickets/<int:pk>/comment/', views.TicketCommentView.as_view(), name='ticket_comment'),
    path('tickets/<int:pk>/work-note/', views.TicketWorkNoteView.as_view(), name='ticket_work_note'),
    path('tickets/<int:pk>/attach/', views.TicketAttachmentUploadView.as_view(), name='ticket_attach'),
    path('tickets/<int:pk>/attachments/<int:attachment_pk>/', views.TicketAttachmentDownloadView.as_view(), name='ticket_attachment_download'),
    path('tickets/<int:pk>/close/', views.TicketCloseView.as_view(), name='ticket_close'),
    path('tickets/<int:pk>/reopen/', views.TicketReopenView.as_view(), name='ticket_reopen'),
    path('incidents/', views.IncidentDashboardView.as_view(), name='incident_dashboard'),
    path('problems/', views.ProblemListView.as_view(), name='problem_list'),
    path('problems/new/', views.ProblemCreateView.as_view(), name='problem_create'),
    path('problems/<int:pk>/', views.ProblemDetailView.as_view(), name='problem_detail'),
    path('suppliers/', views.SupplierListView.as_view(), name='supplier_list'),
    path('suppliers/new/', views.SupplierCreateView.as_view(), name='supplier_create'),
    path('suppliers/<int:pk>/', views.SupplierDetailView.as_view(), name='supplier_detail'),
    path('suppliers/<int:pk>/edit/', views.SupplierUpdateView.as_view(), name='supplier_update'),
    path('suppliers/<int:pk>/deactivate/', views.SupplierDeactivateView.as_view(), name='supplier_deactivate'),
    path('suppliers/<int:pk>/activate/', views.SupplierActivateView.as_view(), name='supplier_activate'),
    path('notifications/', views.NotificationListView.as_view(), name='notification_list'),
    path('notifications/<int:pk>/read/', views.NotificationReadView.as_view(), name='notification_read'),
    path('notifications/read-all/', views.NotificationReadAllView.as_view(), name='notification_read_all'),
    path('sla/', views.SLADashboardView.as_view(), name='sla_dashboard'),
    path('sla/policies/', views.SLAPolicyListView.as_view(), name='sla_policy_list'),
    path('sla/policies/new/', views.SLAPolicyCreateView.as_view(), name='sla_policy_create'),
    path('sla/policies/<int:pk>/edit/', views.SLAPolicyUpdateView.as_view(), name='sla_policy_update'),
    path('problems/<int:pk>/assign/', views.ProblemAssignView.as_view(), name='problem_assign'),
    path('problems/<int:pk>/status/', views.ProblemStatusChangeView.as_view(), name='problem_status_change'),
    path('problems/<int:pk>/comment/', views.ProblemCommentView.as_view(), name='problem_comment'),
    path('problems/<int:pk>/root-cause/', views.ProblemRootCauseView.as_view(), name='problem_root_cause'),
    path('problems/<int:pk>/workaround/', views.ProblemWorkaroundView.as_view(), name='problem_workaround'),
    path('problems/<int:pk>/known-error/', views.ProblemMarkKnownErrorView.as_view(), name='problem_mark_known_error'),
    path('problems/<int:pk>/link-ticket/', views.ProblemLinkTicketView.as_view(), name='problem_link_ticket'),
    path('problems/<int:pk>/unlink-ticket/<int:ticket_pk>/', views.ProblemUnlinkTicketView.as_view(), name='problem_unlink_ticket'),
    path('problems/<int:pk>/rca/', views.ProblemRCAUpdateView.as_view(), name='problem_rca_update'),
    path('problems/<int:pk>/rca/five-whys/', views.ProblemFiveWhysAddView.as_view(), name='problem_five_whys_add'),
    path('problems/<int:pk>/rca/fishbone/', views.ProblemFishboneAddView.as_view(), name='problem_fishbone_add'),
    path('problems/<int:pk>/rca/fishbone/<int:factor_pk>/root-cause/', views.ProblemFishboneRootCauseView.as_view(), name='problem_fishbone_root_cause'),
    path('problems/<int:pk>/rca/evidence/', views.ProblemEvidenceAddView.as_view(), name='problem_evidence_add'),
    path('problems/<int:pk>/rca/actions/', views.ProblemActionAddView.as_view(), name='problem_action_add'),
    path('problems/<int:pk>/rca/actions/<int:action_pk>/status/', views.ProblemActionStatusView.as_view(), name='problem_action_status'),
    path('problems/<int:pk>/rca/approvals/', views.ProblemApprovalRequestView.as_view(), name='problem_approval_request'),
    path('problems/<int:pk>/rca/approvals/<int:approval_pk>/decide/', views.ProblemApprovalDecisionView.as_view(), name='problem_approval_decide'),
    path('problems/<int:pk>/close/', views.ProblemCloseView.as_view(), name='problem_close'),
    path('problems/<int:pk>/reopen/', views.ProblemReopenView.as_view(), name='problem_reopen'),
]