# Generated by Django 5.2.16 on 2026-07-31 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(blank=True, max_length=160)),
                ('contract_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('void', 'Void')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage', models.TextField(blank=True)),
                ('support_phone', models.CharField(blank=True, max_length=40)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='service_desk.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='service_desk.company')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='vendor_management.vendor')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
    ]
