# Generated by Django 5.2.16 on 2026-07-31 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('system', models.CharField(help_text='Target system, e.g. prod-db', max_length=160)),
                ('username', models.CharField(max_length=120)),
                ('environment', models.CharField(default='production', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileged_accounts', to='service_desk.company')),
            ],
            options={
                'ordering': ['system', 'name'],
                'unique_together': {('company', 'system', 'username')},
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('justification', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('requested_minutes', models.PositiveIntegerField(default=60)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pam_approvals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pam_requests', to='service_desk.company')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pam_requests', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pam.privilegedaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivilegedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('audit_trail', models.JSONField(blank=True, default=list)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pam.accessrequest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
