# Generated by Django 5.2.16 on 2026-07-31 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=60)),
                ('scope', models.CharField(choices=[('ticket', 'Ticket'), ('change', 'Change'), ('asset', 'Asset'), ('global', 'Global')], default='ticket', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('stop_on_match', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_rules', to='service_desk.company')),
            ],
            options={
                'ordering': ['priority', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
