apiVersion: v1
kind: Service
metadata:
  name: enterprise-service-desk
  labels:
    app: enterprise-service-desk
spec:
  type: ClusterIP
  selector:
    app: enterprise-service-desk
  ports:
    - name: http
      port: 80
      targetPort: 8000
