# Generated by Django 5.2.16 on 2026-07-31 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='fa-server', max_length=60)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ci_classes', to='service_desk.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('ci_id', models.CharField(max_length=80)),
                ('environment', models.CharField(blank=True, default='production', max_length=40)),
                ('criticality', models.PositiveSmallIntegerField(default=3)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_item', to='service_desk.asset')),
                ('ci_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='cmdb.ciclass')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_items', to='service_desk.company')),
            ],
            options={
                'ordering': ['ci_id'],
                'unique_together': {('company', 'ci_id')},
            },
        ),
        migrations.CreateModel(
            name='DiscoveryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='manual', max_length=80)),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('os_name', models.CharField(blank=True, max_length=120)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_results', to='service_desk.company')),
                ('matched_ci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_hits', to='cmdb.configurationitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CIRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('depends_on', 'Depends on'), ('runs_on', 'Runs on'), ('connects_to', 'Connects to'), ('hosted_on', 'Hosted on'), ('backs_up', 'Backs up'), ('related', 'Related')], default='related', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound', to='cmdb.configurationitem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound', to='cmdb.configurationitem')),
            ],
            options={
                'unique_together': {('source', 'target', 'relation_type')},
            },
        ),
    ]
