# Generated by Django 5.2.16 on 2026-07-31 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('new', 'New'), ('root_cause', 'Root cause analysis'), ('known_error', 'Known error'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('root_cause', models.TextField(blank=True)),
                ('workaround', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='service_desk.company')),
                ('known_error_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_errors', to='service_desk.knowledgearticle')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_problems', to=settings.AUTH_USER_MODEL)),
                ('related_incidents', models.ManyToManyField(blank=True, related_name='related_problems', to='service_desk.ticket')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_record', to='service_desk.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
