# Generated by Django 5.2.16 on 2026-07-31 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=60)),
                ('source_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('tokens', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexed_documents', to='service_desk.company')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['company', 'source_type'], name='document_in_company_8ec73d_idx')],
                'unique_together': {('company', 'source_type', 'source_id')},
            },
        ),
    ]
