# Generated by Django 5.2.16 on 2026-07-31 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='generic', max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('state', models.CharField(choices=[('open', 'Open'), ('acked', 'Acknowledged'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='open', max_length=20)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_alerts', to='service_desk.company')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_alerts', to='service_desk.ticket')),
            ],
            options={
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['company', 'state', 'severity'], name='monitoring__company_7f7cc8_idx'), models.Index(fields=['source', 'external_id'], name='monitoring__source_609721_idx')],
            },
        ),
    ]
