# Generated by Django 5.2.16 on 2026-07-31 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_desk', '0001_initial_enterprise_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(default='update', max_length=60)),
                ('message', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_timeline', to='service_desk.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MajorIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('sev1', 'Severity 1'), ('sev2', 'Severity 2'), ('sev3', 'Severity 3')], default='sev1', max_length=10)),
                ('bridge_channel', models.CharField(blank=True, max_length=255)),
                ('customer_impact', models.TextField(blank=True)),
                ('status_page_url', models.URLField(blank=True)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('postmortem_required', models.BooleanField(default=True)),
                ('postmortem_url', models.URLField(blank=True)),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_incidents', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_incidents', to='service_desk.company')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='major_incident_record', to='service_desk.ticket')),
            ],
            options={
                'ordering': ['-declared_at'],
            },
        ),
    ]
