# Generated by Django 5.2.16 on 2026-08-05 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["name"], name="service_des_name_3e8b89_idx"),
        ),
        migrations.AddIndex(
            model_name="requesttype",
            index=models.Index(fields=["name"], name="service_des_name_09e89b_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="service_des_status_dde7ef_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["priority"], name="service_des_priorit_41ddcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_by"], name="service_des_created_a55979_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assigned_to"], name="service_des_assigne_202781_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["department"], name="service_des_departm_7caebd_idx"
            ),
        ),
    ]
