# Generated by Django 5.2.16 on 2026-08-05 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0002_department_managers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("status_changed", "Status Changed"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("priority_changed", "Priority Changed"),
                            ("urgency_changed", "Urgency Changed"),
                            ("department_changed", "Department Changed"),
                            ("request_type_changed", "Request Type Changed"),
                            ("comment", "Comment Added"),
                            ("attachment", "Attachment Added"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_status", models.CharField(blank=True, default="", max_length=20)),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Ticket History",
                "verbose_name_plural": "Ticket History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="requesttype",
            options={
                "ordering": ["name"],
                "verbose_name": "Request Type",
                "verbose_name_plural": "Request Types",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.AddField(
            model_name="requesttype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="requesttype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="requesttype",
            index=models.Index(
                fields=["is_active"], name="service_des_is_acti_4b283a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["request_type"], name="service_des_request_50b65f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_at"], name="service_des_created_04b69b_idx"
            ),
        ),
        migrations.AddField(
            model_name="tickethistory",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tickethistory",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="service_desk.ticket",
            ),
        ),
        migrations.AddIndex(
            model_name="tickethistory",
            index=models.Index(
                fields=["ticket", "created_at"], name="service_des_ticket__7a698d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickethistory",
            index=models.Index(
                fields=["event_type"], name="service_des_event_t_51de84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickethistory",
            index=models.Index(
                fields=["performed_by"], name="service_des_perform_c82510_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickethistory",
            index=models.Index(
                fields=["created_at"], name="service_des_created_c42800_idx"
            ),
        ),
    ]
