# Generated by Django 5.2.16 on 2026-08-07 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0003_tickethistory_alter_department_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("known_error", "Known Error"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("root_cause", models.TextField(blank=True, default="")),
                ("workaround", models.TextField(blank=True, default="")),
                ("is_known_error", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problems",
                        to="service_desk.department",
                    ),
                ),
                (
                    "related_tickets",
                    models.ManyToManyField(
                        blank=True, related_name="problems", to="service_desk.ticket"
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem",
                "verbose_name_plural": "Problems",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("status_changed", "Status Changed"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("root_cause_updated", "Root Cause Updated"),
                            ("workaround_updated", "Workaround Updated"),
                            ("known_error_declared", "Known Error Declared"),
                            ("ticket_linked", "Ticket Linked"),
                            ("ticket_unlinked", "Ticket Unlinked"),
                            ("comment", "Comment Added"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_status", models.CharField(blank=True, default="", max_length=20)),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problem_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="service_desk.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem History",
                "verbose_name_plural": "Problem History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RootCauseAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("five_whys", "Five Whys"),
                            ("fishbone", "Fishbone (Ishikawa)"),
                            ("fault_tree", "Fault Tree Analysis"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="five_whys",
                        max_length=20,
                    ),
                ),
                ("problem_statement", models.TextField()),
                ("trigger_event", models.TextField(blank=True, default="")),
                ("contributing_factors", models.TextField(blank=True, default="")),
                ("mitigation_steps", models.TextField(blank=True, default="")),
                ("preventative_measures", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_rca_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rca_entries",
                        to="service_desk.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Root Cause Analysis",
                "verbose_name_plural": "Root Cause Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiveWhys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveSmallIntegerField()),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "rca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="five_whys",
                        to="service_desk.rootcauseanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Five Whys Step",
                "verbose_name_plural": "Five Whys Steps",
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="FishboneFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("people", "People"),
                            ("process", "Process"),
                            ("equipment", "Equipment"),
                            ("material", "Material"),
                            ("environment", "Environment"),
                            ("management", "Management"),
                        ],
                        max_length=20,
                    ),
                ),
                ("factor_description", models.TextField()),
                ("is_root_cause", models.BooleanField(default=False)),
                (
                    "rca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fishbone_factors",
                        to="service_desk.rootcauseanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fishbone Factor",
                "verbose_name_plural": "Fishbone Factors",
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file_or_link", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="service_desk.rootcauseanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence",
                "verbose_name_plural": "Evidence",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rca_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="service_desk.rootcauseanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval",
                "verbose_name_plural": "Approvals",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("corrective", "Corrective"),
                            ("preventive", "Preventive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_problem_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="service_desk.rootcauseanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
                "ordering": ["due_date"],
            },
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["status"], name="service_des_status_fdcd06_idx"),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["priority"], name="service_des_priorit_b5207f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["department"], name="service_des_departm_14de99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["assigned_to"], name="service_des_assigne_f4ec7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["created_by"], name="service_des_created_1cf10b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["created_at"], name="service_des_created_9b3222_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemhistory",
            index=models.Index(
                fields=["problem", "created_at"], name="service_des_problem_40bdc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemhistory",
            index=models.Index(
                fields=["event_type"], name="service_des_event_t_23a40b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemhistory",
            index=models.Index(
                fields=["performed_by"], name="service_des_perform_6697b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemhistory",
            index=models.Index(
                fields=["created_at"], name="service_des_created_b53846_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rootcauseanalysis",
            index=models.Index(
                fields=["problem"], name="service_des_problem_61bf6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rootcauseanalysis",
            index=models.Index(fields=["status"], name="service_des_status_5c772d_idx"),
        ),
        migrations.AddIndex(
            model_name="rootcauseanalysis",
            index=models.Index(fields=["method"], name="service_des_method_ac6287_idx"),
        ),
        migrations.AddIndex(
            model_name="rootcauseanalysis",
            index=models.Index(fields=["owner"], name="service_des_owner_i_105a40_idx"),
        ),
        migrations.AddIndex(
            model_name="rootcauseanalysis",
            index=models.Index(
                fields=["created_at"], name="service_des_created_afd95e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fivewhys",
            index=models.Index(
                fields=["rca", "step_number"], name="service_des_rca_id_fa4555_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fivewhys",
            constraint=models.UniqueConstraint(
                fields=("rca", "step_number"), name="unique_five_whys_step_per_rca"
            ),
        ),
        migrations.AddIndex(
            model_name="fishbonefactor",
            index=models.Index(
                fields=["rca", "category"], name="service_des_rca_id_313e38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fishbonefactor",
            index=models.Index(
                fields=["is_root_cause"], name="service_des_is_root_be789e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(fields=["rca"], name="service_des_rca_id_7a29ad_idx"),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["uploaded_at"], name="service_des_uploade_3c633b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(fields=["rca"], name="service_des_rca_id_c4199b_idx"),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(fields=["status"], name="service_des_status_b04f2f_idx"),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["approver"], name="service_des_approve_b16f83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["rca"], name="service_des_rca_id_e8b3fb_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["status"], name="service_des_status_77874b_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["assigned_to"], name="service_des_assigne_08cef6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["due_date"], name="service_des_due_dat_b03bf4_idx"
            ),
        ),
    ]
