# Generated by Django 6.0.7 on 2026-08-01 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0003_customfield_requesttype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requesttype",
            name="department",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="department",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="request_type",
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="title",
            new_name="subject",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="custom_field_values",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="requester",
        ),
        migrations.AddField(
            model_name="ticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("INCIDENT", "Incident"),
                    ("SERVICE_REQUEST", "Service Request"),
                    ("PROBLEM", "Problem"),
                    ("CHANGE", "Change"),
                ],
                default="INCIDENT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_PROGRESS", "In Progress"),
                    ("ON_HOLD", "On Hold"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name="CustomField",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="RequestType",
        ),
    ]
