# Generated by Django 5.2.16 on 2026-08-07 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_desk",
            "0004_problem_problemhistory_rootcauseanalysis_fivewhys_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootcauseanalysis",
            name="problem",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rca",
                to="service_desk.problem",
            ),
        ),
    ]
