# Generated by Django 5.2.16 on 2026-08-07 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0005_alter_rootcauseanalysis_problem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('priority_changed', 'Priority Changed'), ('urgency_changed', 'Urgency Changed'), ('department_changed', 'Department Changed'), ('request_type_changed', 'Request Type Changed'), ('comment', 'Comment Added'), ('work_note', 'Work Note Added'), ('attachment', 'Attachment Added'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('requester_confirmed', 'Requester Confirmed')], max_length=50),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_desk.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Ticket Attachments',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['ticket', 'uploaded_at'], name='service_des_ticket__6659d9_idx'), models.Index(fields=['uploaded_by'], name='service_des_uploade_57f6b0_idx')],
            },
        ),
    ]
