# Generated by Django 5.2.16 on 2026-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0006_alter_tickethistory_event_type_ticketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('closed', 'Closed')], db_index=True, default='open', max_length=30),
        ),
    ]
