# Generated by Django on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0007_alter_ticket_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("contact_name", models.CharField(blank=True, default="", max_length=100)),
                ("contact_email", models.EmailField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="suppliers",
                        to="service_desk.department",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "indexes": [
                    models.Index(fields=["name"], name="service_des_name_bb029f_idx"),
                    models.Index(fields=["department"], name="service_des_departm_85c1f8_idx"),
                    models.Index(fields=["is_active"], name="service_des_is_acti_eccaaa_idx"),
                ],
            },
        ),
    ]
