# Generated by Django 5.2.16 on 2026-08-27 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0008_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, max_length=20)),
                ('response_minutes', models.PositiveIntegerField(help_text='Minutes allowed for the first response.')),
                ('resolution_minutes', models.PositiveIntegerField(help_text='Minutes allowed to resolve the ticket.')),
                ('warning_threshold_percent', models.PositiveSmallIntegerField(default=80, help_text='Percentage of the allowance at which the ticket is flagged as at risk (1-99).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Leave empty for the organisation-wide default for this priority. A department-specific policy always wins over the default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='service_desk.department')),
            ],
            options={
                'verbose_name': 'SLA Policy',
                'verbose_name_plural': 'SLA Policies',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_due_at', models.DateTimeField()),
                ('resolution_due_at', models.DateTimeField()),
                ('first_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response_breached', models.BooleanField(db_index=True, default=False)),
                ('resolution_breached', models.BooleanField(db_index=True, default=False)),
                ('paused', models.BooleanField(default=False, help_text='Set while the ticket is pending on the requester; the clock keeps its deadlines but is excluded from escalation processing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_slas', to='service_desk.slapolicy')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='service_desk.ticket')),
            ],
            options={
                'verbose_name': 'Ticket SLA',
                'verbose_name_plural': 'Ticket SLAs',
                'ordering': ['resolution_due_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('response_warning', 'Response Warning'), ('response_breach', 'Response Breach'), ('resolution_warning', 'Resolution Warning'), ('resolution_breach', 'Resolution Breach')], db_index=True, max_length=32)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ticket_sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='service_desk.ticketsla')),
            ],
            options={
                'verbose_name': 'SLA Escalation',
                'verbose_name_plural': 'SLA Escalations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['priority', 'department'], name='service_des_priorit_69a069_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['is_active'], name='service_des_is_acti_59f5bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.UniqueConstraint(fields=('priority', 'department'), name='unique_sla_policy_per_priority_department'),
        ),
        migrations.AddIndex(
            model_name='ticketsla',
            index=models.Index(fields=['response_due_at'], name='service_des_respons_ffedc0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsla',
            index=models.Index(fields=['resolution_due_at'], name='service_des_resolut_b0b5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsla',
            index=models.Index(fields=['response_breached'], name='service_des_respons_baa05a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsla',
            index=models.Index(fields=['resolution_breached'], name='service_des_resolut_326595_idx'),
        ),
        migrations.AddIndex(
            model_name='slaescalation',
            index=models.Index(fields=['ticket_sla', 'kind'], name='service_des_ticket__5ebe63_idx'),
        ),
        migrations.AddConstraint(
            model_name='slaescalation',
            constraint=models.UniqueConstraint(fields=('ticket_sla', 'kind'), name='unique_sla_escalation_per_kind'),
        ),
    ]
