# Generated by Django 5.2.16 on 2026-08-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0008_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="service_desk.slapolicy",
            ),
        ),
    ]
