# Generated by Django 5.2.16 on 2026-08-09 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0009_slapolicy_ticket_sla_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escalated_at", models.DateTimeField(auto_now_add=True)),
                ("breach_timestamp", models.DateTimeField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_escalations",
                        to="service_desk.ticket",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticket", "breach_timestamp"],
                        name="service_des_ticket__585168_idx",
                    )
                ],
                "unique_together": {("ticket", "breach_timestamp")},
            },
        ),
    ]
