# Generated by Django 5.2.16 on 2026-08-27 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0009_slapolicy_ticketsla_slaescalation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_status_changed', 'Ticket Status Changed'), ('confirmation_requested', 'Confirmation Requested'), ('ticket_confirmed', 'Ticket Confirmed'), ('sla_warning', 'SLA Warning'), ('sla_breach', 'SLA Breach'), ('problem_update', 'Problem Update')], db_index=True, max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('emailed', models.BooleanField(default=False, help_text='True when an email mirror of this notification was successfully handed to the configured email backend.')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='service_desk.problem')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_desk_notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='service_desk.ticket')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='service_des_recipie_779f19_idx'), models.Index(fields=['kind'], name='service_des_kind_f02dfe_idx'), models.Index(fields=['created_at'], name='service_des_created_e3487b_idx')],
            },
        ),
    ]
