# Generated by Django 5.2.16 on 2026-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0010_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickethistory",
            name="from_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="tickethistory",
            name="to_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
