# Generated by Django 5.2.16 on 2026-08-09 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0010_slaescalation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
