# Generated by Django 5.2.16 on 2026-08-28 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0011_expand_ticket_history_status_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ticket_assigned", "Ticket Assigned"),
                    ("ticket_status_changed", "Ticket Status Changed"),
                    ("confirmation_requested", "Confirmation Requested"),
                    ("ticket_confirmed", "Ticket Confirmed"),
                    ("sla_warning", "SLA Warning"),
                    ("sla_breach", "SLA Breach"),
                    ("problem_update", "Problem Update"),
                    ("service_request_approved", "Service Request Approved"),
                    ("service_request_rejected", "Service Request Rejected"),
                    ("service_request_fulfilled", "Service Request Fulfilled"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="service_des_name_061965_idx"),
                    models.Index(
                        fields=["is_active"], name="service_des_is_acti_60b242_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "expected_delivery_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Target calendar days to fulfilment, shown to requesters.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fulfillment_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_catalog_items",
                        to="service_desk.department",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="service_desk.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalogue Item",
                "verbose_name_plural": "Catalogue Items",
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("justification", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("assigned", "Assigned"),
                            ("fulfilling", "Fulfilling"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("expected_fulfillment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="service_desk.catalogitem",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_request",
                        to="service_desk.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_request_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="service_desk.servicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request Approval",
                "verbose_name_plural": "Service Request Approvals",
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("assigned", "Assigned"),
                            ("fulfilling", "Fulfilling"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_request_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="service_desk.servicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request History",
                "verbose_name_plural": "Service Request History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(
                fields=["is_active"], name="service_des_is_acti_d2060d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(
                fields=["category"], name="service_des_categor_1a2f91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(
                fields=["fulfillment_department"], name="service_des_fulfill_80b73b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogitem",
            constraint=models.UniqueConstraint(
                fields=("category", "name"),
                name="unique_catalog_item_name_per_category",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["status"], name="service_des_status_e17203_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["catalog_item"], name="service_des_catalog_d7d46f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["created_at"], name="service_des_created_834576_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestapproval",
            index=models.Index(
                fields=["service_request", "decided_at"],
                name="service_des_service_909f79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequesthistory",
            index=models.Index(
                fields=["service_request", "created_at"],
                name="service_des_service_c06edb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequesthistory",
            index=models.Index(
                fields=["event_type"], name="service_des_event_t_f2aa1d_idx"
            ),
        ),
    ]
