# Generated by Django 5.2.16 on 2026-08-28 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_desk",
            "0012_alter_notification_kind_servicecategory_catalogitem_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("normal", "Normal"),
                            ("emergency", "Emergency"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        help_text="Calculated from impact x urgency at assessment time.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("implementation_plan", models.TextField(blank=True, default="")),
                ("test_plan", models.TextField(blank=True, default="")),
                ("rollback_plan", models.TextField(blank=True, default="")),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("assessed", "Assessed"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("implementing", "Implementing"),
                            ("validation", "Validation"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The implementer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changes",
                        to="service_desk.department",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change",
                "verbose_name_plural": "Changes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="service_desk.change",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Approval",
                "verbose_name_plural": "Change Approvals",
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("submitted", "Submitted"),
                            ("assessed", "Assessed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("scheduled", "Scheduled"),
                            ("implementing", "Implementing"),
                            ("validation", "Validation"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                            ("comment", "Comment Added"),
                            ("assigned", "Assigned"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="service_desk.change",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change History",
                "verbose_name_plural": "Change History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(fields=["status"], name="service_des_status_516c59_idx"),
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(
                fields=["department"], name="service_des_departm_e382ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(
                fields=["assigned_to"], name="service_des_assigne_865585_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(
                fields=["scheduled_start", "scheduled_end"],
                name="service_des_schedul_4ca7e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="changeapproval",
            index=models.Index(
                fields=["change", "decided_at"], name="service_des_change__1d9faa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="changehistory",
            index=models.Index(
                fields=["change", "created_at"], name="service_des_change__3852bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="changehistory",
            index=models.Index(
                fields=["event_type"], name="service_des_event_t_df79ea_idx"
            ),
        ),
    ]
