# Generated by Django 5.2.16 on 2026-08-28 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0013_change_changeapproval_changehistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "version",
                    models.CharField(help_text="e.g. 2026.09.1", max_length=50),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        default="staging",
                        max_length=20,
                    ),
                ),
                ("deployment_plan", models.TextField(blank=True, default="")),
                ("validation_plan", models.TextField(blank=True, default="")),
                ("rollback_plan", models.TextField(blank=True, default="")),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("deploying", "Deploying"),
                            ("validation", "Validation"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Recorded on completion, failure or rollback.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changes",
                    models.ManyToManyField(
                        blank=True, related_name="releases", to="service_desk.change"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="releases",
                        to="service_desk.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Release",
                "verbose_name_plural": "Releases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="service_desk.release",
                    ),
                ),
            ],
            options={
                "verbose_name": "Release Approval",
                "verbose_name_plural": "Release Approvals",
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("scheduled", "Scheduled"),
                            ("deploying", "Deploying"),
                            ("validation", "Validation"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                            ("change_linked", "Change Linked"),
                            ("change_unlinked", "Change Unlinked"),
                            ("owner_assigned", "Owner Assigned"),
                            ("comment", "Comment Added"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="service_desk.release",
                    ),
                ),
            ],
            options={
                "verbose_name": "Release History",
                "verbose_name_plural": "Release History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["status"], name="service_des_status_9fc486_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["department"], name="service_des_departm_8d3203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["owner"], name="service_des_owner_i_939667_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["environment"], name="service_des_environ_33038c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["scheduled_start", "scheduled_end"],
                name="service_des_schedul_0634eb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="unique_release_name_per_version"
            ),
        ),
        migrations.AddIndex(
            model_name="releaseapproval",
            index=models.Index(
                fields=["release", "decided_at"], name="service_des_release_bcfe03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="releasehistory",
            index=models.Index(
                fields=["release", "created_at"], name="service_des_release_823e8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="releasehistory",
            index=models.Index(
                fields=["event_type"], name="service_des_event_t_27c446_idx"
            ),
        ),
    ]
