# Generated by Django 5.2.16 on 2026-08-28 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0014_release_releaseapproval_releasehistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Configuration Item Type",
                "verbose_name_plural": "Configuration Item Types",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="service_des_name_4e548e_idx"),
                    models.Index(
                        fields=["is_active"], name="service_des_is_acti_9d288f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "identifier",
                    models.CharField(
                        help_text="Asset tag, serial number, or other unique identifier.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_service", "In Service"),
                            ("in_repair", "In Repair"),
                            ("in_stock", "In Stock"),
                            ("retired", "Retired"),
                            ("disposed", "Disposed"),
                        ],
                        db_index=True,
                        default="in_service",
                        max_length=20,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="configuration_items",
                        to="service_desk.change",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuration_items",
                        to="service_desk.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_configuration_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tickets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="configuration_items",
                        to="service_desk.ticket",
                    ),
                ),
                (
                    "ci_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="service_desk.configurationitemtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Item",
                "verbose_name_plural": "Configuration Items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CIRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("depends_on", "Depends On"),
                            ("connects_to", "Connects To"),
                            ("hosts", "Hosts"),
                            ("runs_on", "Runs On"),
                            ("part_of", "Part Of"),
                            ("backs_up", "Backs Up"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ci_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="service_desk.configurationitem",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="service_desk.configurationitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "CI Relationship",
                "verbose_name_plural": "CI Relationships",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source"], name="service_des_source__8f6d88_idx"
                    ),
                    models.Index(
                        fields=["target"], name="service_des_target__431590_idx"
                    ),
                    models.Index(
                        fields=["relationship_type"],
                        name="service_des_relatio_95c790_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source", models.F("target")), _negated=True
                        ),
                        name="ci_relationship_no_self_reference",
                    ),
                    models.UniqueConstraint(
                        fields=("source", "target", "relationship_type"),
                        name="unique_ci_relationship",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="configurationitem",
            index=models.Index(fields=["status"], name="service_des_status_f33f3b_idx"),
        ),
        migrations.AddIndex(
            model_name="configurationitem",
            index=models.Index(
                fields=["criticality"], name="service_des_critica_94c61e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configurationitem",
            index=models.Index(
                fields=["department"], name="service_des_departm_318fa2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configurationitem",
            index=models.Index(fields=["owner"], name="service_des_owner_i_66767a_idx"),
        ),
        migrations.AddIndex(
            model_name="configurationitem",
            index=models.Index(
                fields=["ci_type"], name="service_des_ci_type_093e1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configurationitem",
            index=models.Index(
                fields=["identifier"], name="service_des_identif_c0733e_idx"
            ),
        ),
    ]
