# Generated by Django 5.2.16 on 2026-08-28 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0015_configurationitemtype_configurationitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Knowledge Category",
                "verbose_name_plural": "Knowledge Categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="service_des_name_c16c1b_idx"),
                    models.Index(
                        fields=["is_active"], name="service_des_is_acti_8fa344_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("tags", models.CharField(blank=True, default="", max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public (all users)"),
                            ("internal", "Internal (staff only)"),
                            ("restricted", "Restricted (managers and administrators)"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_knowledge_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_articles_to_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="service_desk.knowledgecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Article",
                "verbose_name_plural": "Knowledge Articles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_helpful", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to="service_desk.knowledgearticle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Feedback",
                "verbose_name_plural": "Knowledge Feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeArticleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("submitted_for_review", "Submitted For Review"),
                            ("reviewer_assigned", "Reviewer Assigned"),
                            ("approved", "Approved"),
                            ("sent_back", "Sent Back"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("revision_started", "Revision Started"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="service_desk.knowledgearticle",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_article_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Article History",
                "verbose_name_plural": "Knowledge Article History",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["article", "created_at"],
                        name="service_des_article_3f3a90_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="service_des_event_t_0c323f_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(fields=["status"], name="service_des_status_57d518_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(
                fields=["visibility"], name="service_des_visibil_ef45c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(
                fields=["category"], name="service_des_categor_458a84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(
                fields=["author"], name="service_des_author__4d44df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgefeedback",
            index=models.Index(
                fields=["article", "is_helpful"], name="service_des_article_bbaa59_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgefeedback",
            constraint=models.UniqueConstraint(
                fields=("article", "user"), name="unique_knowledge_feedback_per_user"
            ),
        ),
    ]
