# Generated by Django 5.2.16 on 2026-08-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_desk",
            "0016_knowledgecategory_knowledgearticle_knowledgefeedback_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SLARunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("warnings_count", models.PositiveIntegerField(default=0)),
                ("breaches_count", models.PositiveIntegerField(default=0)),
                ("succeeded", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "SLA Run Log",
                "verbose_name_plural": "SLA Run Logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["started_at"], name="service_des_started_34e330_idx"
                    ),
                    models.Index(
                        fields=["succeeded"], name="service_des_succeed_526d52_idx"
                    ),
                ],
            },
        ),
    ]
